name: React Frontend CI/CD Pipeline

# This workflow handles the CI/CD process for the React frontend
# It builds, tests, and deploys the React application to S3

# Trigger on push to main branch or pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Environment variables
env:
  AWS_REGION: ${{ secrets.AWS_REGION }} # Change to your preferred region
  S3_BUCKET: react-app-bucket-raj # Change to your bucket name
  SKIP_PREFLIGHT_CHECK: true # Skip Create React App dependency checks

# Permissions for OIDC authentication
permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Latest LTS version as of March 2025
          cache: 'npm'
          cache-dependency-path: './package-lock.json'

      # Install dependencies with legacy-peer-deps to handle @material-ui/core with React 18
      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      # Create or update .env file with SKIP_PREFLIGHT_CHECK
      - name: Setup Environment
        run: |
          echo "SKIP_PREFLIGHT_CHECK=true" >> .env
          cat .env

      # Build the React app with CI=false to ignore warnings
      - name: Build
        run: npm run build
        env:
          CI: false  # Don't treat warnings as errors

      # Configure AWS credentials using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ARN }}
          role-session-name: react-app-session
          aws-region: ${{ secrets.AWS_REGION }}

      # Sync build folder to S3
      - name: Deploy to S3
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
        run: |
          aws s3 sync ./build/ s3://${{ env.S3_BUCKET }}/ \
            --delete \
            --cache-control "public, max-age=31536000" \
            --exclude "*.html" \
            --exclude "service-worker.js"
          
          # Handle HTML files separately with no-cache
          aws s3 sync ./build/ s3://${{ env.S3_BUCKET }}/ \
            --delete \
            --cache-control "no-store, no-cache, must-revalidate" \
            --include "*.html" \
            --include "service-worker.js"